tinylab_test_code: Include TimeLib.h
Fix compilation error

    In file included from ...\tinylab_test_code\tinylab_test_code.ino:30:0:
    ....\Arduino\libraries\DS1307RTC/DS1307RTC.h:19:22: errror: 'tmElements_t' has not been declared
        static bool read(tmElements_t &tm);

Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>